{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Network Up",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_up{job=\"Device1_NodeExport\"}"
    }
   ]
  },
  {
   "title": "Physical Cores",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_cpu_physical_cores{job=\"secondDevice_cAdvisor\"}"
    }
   ]
  },
  {
   "title": "Total System Cores",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_cpu_cores{job=\"secondDevice_cAdvisor\"}"
    }
   ]
  },
  {
   "title": "System Threads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_threads{job=\"Device1_NodeExport\"}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "100 * (\n  (node_memory_MemTotal_bytes{job=\"Device1_NodeExport\"} - node_memory_MemAvailable_bytes{job=\"Device1_NodeExport\"})\n  / node_memory_MemTotal_bytes{job=\"Device1_NodeExport\"}\n)"
    }
   ]
  },
  {
   "title": "Load on the System [1m]",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{job=\"Device1_NodeExport\"}"
    }
   ]
  },
  {
   "title": "Temperature Visualizer",
   "type": "bargauge",
   "description": "node_hwmon_temp_celsius",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{job=\"Device1_NodeExport\"}"
    }
   ]
  },
  {
   "title": "CPU Boot Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "targets": [
    {
     "expr": "node_boot_time_seconds{job=\"Device1_NodeExport\"}"
    }
   ]
  },
  {
   "title": "Network Receive and Send[Bytes]",
   "type": "timeseries",
   "description": "node_network_receive_bytes_ (all u want)",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{job=\"Device1_NodeExport\"}"
    },
    {
     "expr": "node_network_transmit_bytes_total{job=\"Device1_NodeExport\"}"
    }
   ]
  },
  {
   "title": "Hover to See Prod INFO",
   "type": "timeseries",
   "description": "node_dmi_info",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 22 },
   "targets": [
    {
     "expr": "node_dmi_info{job=\"Device1_NodeExport\"}"
    }
   ]
  },
  {
   "title": "CPU Seconds Total",
   "type": "timeseries",
   "description": "node_cpu_seconds_total",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 22 },
   "targets": [
    {
     "expr": "node_cpu_seconds_total{job=\"Device1_NodeExport\"}"
    }
   ]
  },
  {
   "title": "Free Bytes in Filesystem",
   "type": "piechart",
   "description": "node_filesystem_free_bytes",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{job=\"Device1_NodeExport\"}"
    }
   ]
  },
  {
   "title": "Memory Exhaustion Events",
   "type": "timeseries",
   "description": "node_vmstat_oom_kill",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
   "targets": [
    {
     "expr": "node_vmstat_oom_kill{job=\"Device1_NodeExport\"}"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "timeseries",
   "description": "node_memory_MemFree_bytes",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"Device1_NodeExport\"}"
    }
   ]
  },
  {
   "title": "Container Memory Related",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "container_memory_cache{job=\"secondDevice_cAdvisor\"}"
    },
    {
     "expr": "container_memory_failures_total{job=\"secondDevice_cAdvisor\"}"
    },
    {
     "expr": "container_memory_usage_bytes{job=\"secondDevice_cAdvisor\"}"
    }
   ]
  },
  {
   "title": "Container FS Reads Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "container_fs_reads_total{job=\"secondDevice_cAdvisor\"}"
    }
   ]
  },
  {
   "title": "Network Flags",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "node_network_flags{job=\"Device1_NodeExport\"}"
    }
   ]
  },
  {
   "title": "Over the Network Things",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 43 },
   "targets": [
    {
     "expr": "container_network_receive_packets_total{job=\"secondDevice_cAdvisor\"}"
    },
    {
     "expr": "container_network_receive_packets_dropped_total{job=\"secondDevice_cAdvisor\"}"
    },
    {
     "expr": "rate(container_network_transmit_packets_total{job=\"secondDevice_cAdvisor\"}[$__rate_interval])"
    },
    {
     "expr": "container_network_transmit_bytes_total{job=\"secondDevice_cAdvisor\"}"
    }
   ]
  },
  {
   "title": "Container CPU Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "container_cpu_load_average_10s{job=\"Device1_cAdvisor\"}"
    }
   ]
  },
  {
   "title": "Service Monitoring",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 50 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{job=\"cadvisor\"}"
    }
   ]
  },
  {
   "title": "SYSTEM LOGS",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/remote/psipl-HP-280-G3-SFF-Business-PC.log\"} |= ``"
    }
   ]
  }
 ]
}